//For login
export const LOGIN_LOADING="LOGIN LOADING";
export const LOGIN_STUDENT_SUCCESS="LOGIN_STUDENT_SUCCESS";
export const LOGIN_ERROR="LOGIN_ERROR";

//For Signup
export const SIGNUP_LOADING="SIGNUP_LOADING";
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
export const SIGNUP_ERROR="SIGNUP_ERROR";

//For Profile Fetch
export const PROFILE_LOADING="PROFILE_LOADING";
export const PROFILE_SUCCESS="PROFILE_SUCCESS";
export const PROFILE_ERROR="PROFILE_ERROR";

//Get Courses 
export const GET_COURSE_LOADING="GET_COURSE_LOADING";
export const GET_COURSE_SUCCESS="GET_COURSE_SUCCESS";
export const GET_COURSE_ERROR="GET_COURSE_ERROR";

export const SUBSCRIPTIONS_LOADING="SUBSCRIPTIONS_LOADING";
export const SUBSCRIPTIONS_SUCCESS="SUBSCRIPTIONS_SUCCESS";
export const SUBSCRIPTIONS_ERROR="SUBSCRIPTIONS_ERROR";

export const TESTS_LOADING="TESTS_LOADING";
export const TESTS_SUCCESS="TESTS_SUCCESS";
export const TESTS_ERROR="TESTS_ERROR";

export const QUESTIONS_LOADING= "QUESTIONS_LOADING";
export const QUESTIONS_SUCCESS= "QUESTIONS_SUCCESS";
export const QUESTIONS_ERROR= "QUESTIONS_ERROR";

export const SCORE="SCORE";
//Student Logout
export const STUDENT_LOGOUT="STUDENT_LOGOUT";